# Generated by Django 4.0.4 on 2022-11-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smalldata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='language',
            field=models.CharField(default='de', max_length=2),
        ),
    ]
